#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


cd "${BASE_DIR}"
git submodule update --init --recursive


# ------------------------------------------------------------------------------------------------ #
# Verify dotbot config files exist.
# Also checks if the config file exists if it has a suffix of '-sudo'. Ex: apt-sudo
# Checks if the file exists in meta/configs/ folder
# Exits program if a dotbot config doesn't exist

sudoSuffix="-sudo"
exitIfConfigNotFound=false    # used as a flag to exit IF a config file is NOT found
for config in ${@}; do
    # remove suffix '-sudo' in the variable $config
    # check if the config filepath doesn't exist
    #   print message
    #   flag variable to exit

    # remove suffix '-sudo'
    # obtained from https://stackoverflow.com/a/16623897/3053548
    config=${config%"$sudoSuffix"}
    configFilepath="${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
    if [[ ! -e $configFilepath ]]; then
      echo -e "Dotbot config \\033[1;31m$configFilepath \\033[0mDOESN'T exists"

      exitIfConfigNotFound=true
    fi
done

# exit if a config filepath is NOT found
if [[ $exitIfConfigNotFound == true ]]; then
    echo -e "\nexiting"
    exit 1
fi

# cleanup variables
unset sudoSuffix
unset exitIfConfigNotFound

# ------------------------------------------------------------------------------------------------ #
for config in ${@}; do
    # create temporary file
    configFile="$(mktemp)"
    suffix="-sudo"
    echo -e "$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config%"$suffix"}${CONFIG_SUFFIX}")" > "$configFile"

    cmd=("${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "$configFile")

    # print a line depending on the terminal width
    # get terminal width: https://unix.stackexchange.com/a/425158
    # print a line of   : https://stackoverflow.com/a/17030976/3053548
    printf '%0.s=' $(seq 1 $(stty size | awk '{print $2}'))
    printf '%0.s=' $(seq 1 $(stty size | awk '{print $2}'))
    echo -e "\nConfigure $config\n"

    if [[ $config == *"sudo"* ]]; then
        cmd=(sudo "${cmd[@]}")
    fi

    "${cmd[@]}"
    rm -f "$configFile"
done

cd "${BASE_DIR}"

echo "Restart your terminal..."

